name: hollywood_conta
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
   sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  cloud_firestore: ^4.3.2
  provider: ^6.0.5
  uuid: ^3.0.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  flutter_native_splash: ^2.0.1+1
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#0076DB"
  image: assets/icon.png
  color_dark: "#121212"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
